### ISSUE TITLE
怎么用

### ISSUE THREAD

**Issue by lurongjiang** [colorknight/moql#8]
怎么用的,输出一直是NULL,参考文档不是很详细,是哪里使用有问题
```java

@Test
	public void testTrans() throws Exception {
		List<UserBean> jsonArray = new ArrayList<>();
		for (int i = 0; i < 10; i++) {
			UserBean obj = new UserBean();
			obj.name = "Jack";
			obj.age = 20;
			jsonArray.add(obj);
		}
	/*	List<Map<String, Object>> jsonArray = new ArrayList<>();
		for (int i = 0; i < 10; i++) {
			Map<String, Object> obj = new HashMap<>();
			obj.put("name", "Jack");
			obj.put("age", 20);
			jsonArray.add(obj);
		}*/
		DataSetMap dataSetMap = new DataSetMapImpl();
		dataSetMap.putDataSet("UserInfo", jsonArray);
		String sql = "select name,age from UserInfo";
		Selector selector = MoqlEngine.createSelector(sql);
		selector.select(dataSetMap);
		RecordSet recordSet = selector.getRecordSet();
		outputRecordSet(recordSet);
	}

	private static class UserBean {
		private String name;
		private Integer age;

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public Integer getAge() {
			return age;
		}

		public void setAge(Integer age) {
			this.age = age;
		}
	}

```

**Comment by colorknight** [comment]
试试sql写成这样：select u.name, u.age from UserInfo u，因为咱们链表里是bean对象，moql是不知道对象中有啥的，你必须显示告诉moql怎么访问bean对象，u.name就是告诉moql获取bean对象的name属性，如果u.getAge()，就是告诉moql去调用bean对象的getAge()方法了

**Comment by lurongjiang** [comment]
@colorknight 貌似有效,但是又又有一个问题
这个SQL应该是符合SQL标准的,但是执行报错...
```sql
select u.name as nm,u.age as ag from UserInfo u where u.ag>10
```

output

```
line 1:14 mismatched input 'as' expecting FROM

org.datayoo.moql.MoqlException: Parse moql 'select u.name as nm,u.age as ag from UserInfo u where u.ag>10' failed!

	at org.datayoo.moql.parser.MoqlParser.parseMoql(MoqlParser.java:50)
	at org.datayoo.moql.parser.MoqlParser.parseMoql(MoqlParser.java:33)
	at org.datayoo.moql.engine.MoqlEngine.createSelector(MoqlEngine.java:52)
....
```

**Comment by colorknight** [comment]
我本地测试了你的sql， 没问题，可以解析。解析语法结构如下：
`<selector xmlns="http://www.datayoo.org/schema/moql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.datayoo.org/schema/moql selector-base.xsd">
  <cache size="0"/>
  <columns>
    <column name="nm" value="u.name"/>
    <column name="ag" value="u.age"/>
  </columns>
  <tables>
    <table name="u" value="UserInfo"/>
  </tables>
  <where>
    <binary loperand="u.age" operator="&gt;" roperand="10"/>
  </where>
</selector>`
代码如下：
`      String sql = "select u.name as nm,u.age as ag from UserInfo u where u.age>10";
      SelectorDefinition selectorDefinition = MoqlParser.parseMoql(sql, true);
      System.out.println(MoqlParser.translateMetadata2Xml(selectorDefinition));`

**Comment by lurongjiang** [comment]
@colorknight 我也纳闷....
![微信截图_20240223150644](https://github.com/colorknight/moql/assets/44705885/0cda0efb-7eac-4e80-ad96-3800165b994e)

**Comment by colorknight** [comment]
源码模式下：是不是你moql-meta模块，你没有重新编译一下antlr
jar包模式下：你是不是用的jar包不够新？

**Comment by lurongjiang** [comment]
@colorknight 

看起来好像是,之前的dependencies是这个
```xml
        <dependency>
            <groupId>org.datayoo.moql</groupId>
            <artifactId>moql-engine</artifactId>
            <version>1.3.9</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.moql</groupId>
            <artifactId>moql-meta</artifactId>
            <version>1.1.7</version>
        </dependency>
```
改成
```xml
        <dependency>
            <groupId>org.datayoo.moql</groupId>
            <artifactId>moql-engine</artifactId>
            <version>1.4.8</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.moql</groupId>
            <artifactId>moql-meta</artifactId>
            <version>1.2.2</version>
        </dependency>
```
后运行可以了

这两个模块版本兼容性矩阵可以考虑做一下,两个版本不一致,不知道用哪个版本

**Comment by colorknight** [comment]
好的。这之前应该是有个bug，解析的有问题，后来做了些修复。
